; Script generated by the HM NIS Edit Script Wizard.

ManifestDPIAware true

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "OpenUtau Lunai"
!define PRODUCT_PUBLISHER "keirokeer"
!define PRODUCT_WEB_SITE "https://lunaiproject.github.io/editor"
!define PRODUCT_EXE "OpenUtau-Lunai.exe"
!define PRODUCT_PROGID "OpenUtauLunaiFile"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

; MUI 1.8 compatible ------
!include "MUI2.nsh"
!include "FileFunc.nsh"
!insertmacro GetParameters
!insertmacro GetOptions

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "OpenUtau\Assets\open-utau.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Language Selection Dialog Settings
!define MUI_LANGDLL_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_LANGDLL_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_LANGDLL_REGISTRY_VALUENAME "NSIS:Language"

Var IsAppUpdate

; Skip wizard chrome for in-app updates (/UPDATE): keep Instfiles progress only.
Function SkipIfAppUpdate
  StrCmp $IsAppUpdate 1 0 +2
  Abort
FunctionEnd

; Welcome page
!define MUI_PAGE_CUSTOMFUNCTION_PRE SkipIfAppUpdate
!insertmacro MUI_PAGE_WELCOME
; Directory page (first-time / manual installs only)
!define MUI_PAGE_CUSTOMFUNCTION_PRE SkipIfAppUpdate
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page (always shown unless fully silent /S)
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_PAGE_CUSTOMFUNCTION_PRE SkipIfAppUpdate
!define MUI_FINISHPAGE_RUN "$INSTDIR\${PRODUCT_EXE}"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "French"
!insertmacro MUI_LANGUAGE "German"
!insertmacro MUI_LANGUAGE "Japanese"
!insertmacro MUI_LANGUAGE "Korean"
!insertmacro MUI_LANGUAGE "Russian"
!insertmacro MUI_LANGUAGE "SimpChinese"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "OpenUtau-Lunai-win-${ARCH}.exe"
InstallDir "$PROGRAMFILES64\OpenUtau-Lunai"
; Remember last install dir for upgrades (Directory page + /D= from app updater).
InstallDirRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "InstallLocation"
ShowInstDetails show
ShowUnInstDetails show

Function .onInit
  StrCpy $IsAppUpdate 0
  ${GetParameters} $R0
  ClearErrors
  ${GetOptions} $R0 "/UPDATE" $R1
  IfErrors check_silent
  StrCpy $IsAppUpdate 1
check_silent:

  ; First-time / manual: language dialog. /S and /UPDATE: skip it.
  StrCmp $IsAppUpdate 1 skip_lang
  IfSilent skip_lang
  !insertmacro MUI_LANGDLL_DISPLAY
skip_lang:

  ; Close promptly after Instfiles when updating from the app (Finish is skipped).
  StrCmp $IsAppUpdate 1 0 +2
  SetAutoClose true
FunctionEnd

Section "MainSection" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite on
  File "bin\win-${ARCH}\*"
SectionEnd

Section -AdditionalIcons
  CreateShortCut "$SMPROGRAMS\OpenUtau Lunai.lnk" "$INSTDIR\${PRODUCT_EXE}"
  CreateShortCut "$DESKTOP\OpenUtau Lunai.lnk" "$INSTDIR\${PRODUCT_EXE}"
SectionEnd

Section -Post
  ;leave a mark that the program was installed
  FileOpen $9 "$INSTDIR\installed.txt" w
  FileWrite $9 "yes"
  FileClose $9

  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\${PRODUCT_EXE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "InstallLocation" "$INSTDIR"

  ; Remove leftover nested binary install (old OpenUtau\ shadow) that can load a stale Core DLL.
  IfFileExists "$INSTDIR\OpenUtau\OpenUtau.Core.dll" 0 skip_nested_cleanup
  RMDir /r "$INSTDIR\OpenUtau"
skip_nested_cleanup:

  WriteRegStr HKCR ".ustx" "" "${PRODUCT_PROGID}"
  WriteRegStr HKCR "${PRODUCT_PROGID}" "" "OpenUtau Sequence File"
  WriteRegStr HKCR "${PRODUCT_PROGID}\DefaultIcon" "" "$INSTDIR\${PRODUCT_EXE}"
  WriteRegStr HKCR "${PRODUCT_PROGID}\shell\open\command" "" '"$INSTDIR\${PRODUCT_EXE}" "%1"'
SectionEnd

Section "VC Redist"
  SetOutPath "$INSTDIR"
  File "vc_redist.${ARCH}.exe"
  ; Quiet so updates do not pop a second wizard; first install also fine without UI.
  ExecWait '"$INSTDIR\vc_redist.${ARCH}.exe" /install /quiet /norestart'
  Delete "$INSTDIR\vc_redist.${ARCH}.exe"
SectionEnd

Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) was successfully removed from your computer."
FunctionEnd

Function un.onInit
!insertmacro MUI_UNGETLANGUAGE
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "Are you sure you want to completely remove $(^Name) and all of its components?" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\*"
  RMDir "$INSTDIR"

  Delete "$SMPROGRAMS\OpenUtau Lunai.lnk"
  Delete "$DESKTOP\OpenUtau Lunai.lnk"

  ; Only clear .ustx association if it still points at Lunai.
  ReadRegStr $0 HKCR ".ustx" ""
  StrCmp $0 "${PRODUCT_PROGID}" 0 skip_ustx
  DeleteRegKey HKCR ".ustx"
skip_ustx:
  DeleteRegKey HKCR "${PRODUCT_PROGID}"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  SetAutoClose true
SectionEnd
